# NUMPY MODULE / LIBRARY 

In [2]:
import numpy as np

In [3]:
np.version

<module 'numpy.version' from 'C:\\Users\\chara\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [4]:
np.__version__ # to check the version of module

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating LIST

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list) #returns type of data type

list

# converting list to array

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

# arange() function
- arange() is a function in the NumPy library that returns an array with evenly spaced values within a given range.

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10)

array([], dtype=int32)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
ar = np.arange(-30,20) 
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

# zeros() function
- zeros() is a function in the NumPy library that creates an array filled with all zeros.
- PARAMETER TUNING : system uses its own parameters
- HYPERPARAMETER TUNING : user changes the system parameters

In [20]:
np.zeros(10) # parameter tuning - sys use its own parameter

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(10,dtype = int) # hyperparameter tuning - user change the sys parameters

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.zeros((2,2), dtype = int) # 2D ARRAY

array([[0, 0],
       [0, 0]])

In [23]:
np.zeros((3,3), dtype = int)  # 3D ARRAY

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.zeros((2,10), dtype = int) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.zeros((10,10), dtype = int) # nD ARRAY

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# ones() function
- ones() is a function in the NumPy library that creates an array filled with all ones.

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
np.three((2,2)) # only zeros and ones will work

AttributeError: module 'numpy' has no attribute 'three'

- its an error, coz there is no three() function in numpy module/library 

In [54]:
rand(3,2) 

NameError: name 'rand' is not defined

In [55]:
random.rand(3,2)

NameError: name 'random' is not defined

- error coz, random and rand are not defined before executing 

# random() function
- random() is a function in the NumPy library (under np.random) used to generate random numbers.
- np.random.randint() is a NumPy function used to generate random integers (whole numbers) in a specified range.

In [29]:
np.random.rand(5)

array([0.15703469, 0.97546287, 0.18971722, 0.45323576, 0.69410315])

In [30]:
np.random.rand(5)

array([0.821097  , 0.03626323, 0.17570078, 0.85624371, 0.83103987])

In [31]:
np.random.rand(3,5)

array([[0.90502209, 0.50391037, 0.90600036, 0.43547177, 0.13859078],
       [0.78098841, 0.25851131, 0.12868712, 0.70658498, 0.83942283],
       [0.52795846, 0.82280768, 0.47797701, 0.46386942, 0.07753883]])

In [32]:
np.random.randint(3,5)

4

In [33]:
np.random.randint(3,9) # returns the value in random and less than 2nd argument

3

In [34]:
np.random.randint(3,9,5) 

array([3, 6, 3, 4, 6])

In [35]:
np.random.randint(3,9,(10,10))

array([[5, 8, 5, 5, 8, 5, 3, 3, 5, 6],
       [3, 8, 7, 4, 7, 7, 3, 3, 3, 3],
       [4, 8, 6, 6, 5, 3, 6, 4, 3, 8],
       [5, 7, 3, 3, 4, 7, 7, 7, 7, 3],
       [4, 3, 4, 3, 4, 4, 8, 6, 5, 8],
       [3, 6, 3, 6, 7, 8, 3, 4, 6, 6],
       [3, 6, 7, 5, 5, 6, 5, 3, 7, 6],
       [8, 7, 5, 7, 6, 5, 6, 6, 6, 4],
       [7, 6, 3, 4, 7, 5, 6, 6, 4, 7],
       [4, 5, 4, 7, 5, 3, 6, 4, 4, 7]])

In [36]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# slicing in matrix
- Slicing is used to extract specific sub-arrays or parts of a matrix (2D array). In NumPy, you can use slicing to access specific rows, columns, or sub-matrices of a 2D array.

In [37]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 18, 11, 11],
       [18, 14, 18, 18],
       [17, 19, 19, 11],
       [17, 19, 17, 10],
       [13, 16, 13, 17]])

In [38]:
type(b)

numpy.ndarray

In [39]:
b

array([[13, 18, 11, 11],
       [18, 14, 18, 18],
       [17, 19, 19, 11],
       [17, 19, 17, 10],
       [13, 16, 13, 17]])

In [40]:
b[:]

array([[13, 18, 11, 11],
       [18, 14, 18, 18],
       [17, 19, 19, 11],
       [17, 19, 17, 10],
       [13, 16, 13, 17]])

In [41]:
b[1:3]

array([[18, 14, 18, 18],
       [17, 19, 19, 11]])

In [42]:
b[0]

array([13, 18, 11, 11])

In [43]:
b[1]

array([18, 14, 18, 18])

In [44]:
b[1,2]

18

In [45]:
b

array([[13, 18, 11, 11],
       [18, 14, 18, 18],
       [17, 19, 19, 11],
       [17, 19, 17, 10],
       [13, 16, 13, 17]])

In [46]:
b[1,-1]

18

In [47]:
b[2:3]

array([[17, 19, 19, 11]])

In [48]:
b[0:-2]

array([[13, 18, 11, 11],
       [18, 14, 18, 18],
       [17, 19, 19, 11]])

In [49]:
b[0,2]

11

In [50]:
b

array([[13, 18, 11, 11],
       [18, 14, 18, 18],
       [17, 19, 19, 11],
       [17, 19, 17, 10],
       [13, 16, 13, 17]])

In [51]:
b[-5,-3]

18

In [52]:
b[-4,2]

18

# Operations

In [54]:
a = np.random.randint(10,20,10) # (start, stop, step)
a

array([11, 17, 15, 11, 15, 16, 14, 18, 13, 15])

In [55]:
# __init__ is a constructor
# __name__ too (bydefault it calls main)

In [56]:
id(a) # id : address of a variable

2701459484240

In [57]:
arr

array([0, 1, 2, 3, 4, 5])

In [58]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[41, 81, 73, 28, 20, 34, 68, 44, 16, 13],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36],
       [43, 66, 50, 51, 15,  1, 58, 44, 25, 75],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [43, 38, 46, 25, 55, 78, 30, 21, 31, 73],
       [10, 44, 71, 26, 27, 39, 94, 61, 63,  3],
       [79, 63, 44, 84, 32, 99, 98,  8, 35, 18],
       [82, 97, 88, 57, 65, 64, 32,  8, 74, 72],
       [65, 22, 11, 22,  9, 24, 65, 51, 56,  8],
       [99, 12, 44, 36, 49,  5, 56, 86, 96, 97]])

In [59]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [60]:
arr

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[:4]

array([0, 1, 2, 3])

In [63]:
arr2[:]

array([[41, 81, 73, 28, 20, 34, 68, 44, 16, 13],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36],
       [43, 66, 50, 51, 15,  1, 58, 44, 25, 75],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [43, 38, 46, 25, 55, 78, 30, 21, 31, 73],
       [10, 44, 71, 26, 27, 39, 94, 61, 63,  3],
       [79, 63, 44, 84, 32, 99, 98,  8, 35, 18],
       [82, 97, 88, 57, 65, 64, 32,  8, 74, 72],
       [65, 22, 11, 22,  9, 24, 65, 51, 56,  8],
       [99, 12, 44, 36, 49,  5, 56, 86, 96, 97]])

In [65]:
arr2[0:5]

array([[41, 81, 73, 28, 20, 34, 68, 44, 16, 13],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36],
       [43, 66, 50, 51, 15,  1, 58, 44, 25, 75],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [43, 38, 46, 25, 55, 78, 30, 21, 31, 73]])

In [66]:
arr2

array([[41, 81, 73, 28, 20, 34, 68, 44, 16, 13],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36],
       [43, 66, 50, 51, 15,  1, 58, 44, 25, 75],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [43, 38, 46, 25, 55, 78, 30, 21, 31, 73],
       [10, 44, 71, 26, 27, 39, 94, 61, 63,  3],
       [79, 63, 44, 84, 32, 99, 98,  8, 35, 18],
       [82, 97, 88, 57, 65, 64, 32,  8, 74, 72],
       [65, 22, 11, 22,  9, 24, 65, 51, 56,  8],
       [99, 12, 44, 36, 49,  5, 56, 86, 96, 97]])

# Advanced slicing in Matrix
- Advanced slicing allows more control over the selection of elements in a matrix. You can specify a step size (like skipping rows or columns), or use more complex patterns to slice your array.

In [67]:
arr2[::-1] #returns reverse array

array([[99, 12, 44, 36, 49,  5, 56, 86, 96, 97],
       [65, 22, 11, 22,  9, 24, 65, 51, 56,  8],
       [82, 97, 88, 57, 65, 64, 32,  8, 74, 72],
       [79, 63, 44, 84, 32, 99, 98,  8, 35, 18],
       [10, 44, 71, 26, 27, 39, 94, 61, 63,  3],
       [43, 38, 46, 25, 55, 78, 30, 21, 31, 73],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [43, 66, 50, 51, 15,  1, 58, 44, 25, 75],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36],
       [41, 81, 73, 28, 20, 34, 68, 44, 16, 13]])

In [68]:
arr2

array([[41, 81, 73, 28, 20, 34, 68, 44, 16, 13],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36],
       [43, 66, 50, 51, 15,  1, 58, 44, 25, 75],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [43, 38, 46, 25, 55, 78, 30, 21, 31, 73],
       [10, 44, 71, 26, 27, 39, 94, 61, 63,  3],
       [79, 63, 44, 84, 32, 99, 98,  8, 35, 18],
       [82, 97, 88, 57, 65, 64, 32,  8, 74, 72],
       [65, 22, 11, 22,  9, 24, 65, 51, 56,  8],
       [99, 12, 44, 36, 49,  5, 56, 86, 96, 97]])

In [69]:
arr2[::-2] #returns in reverse and its takes -2 as step

array([[99, 12, 44, 36, 49,  5, 56, 86, 96, 97],
       [82, 97, 88, 57, 65, 64, 32,  8, 74, 72],
       [10, 44, 71, 26, 27, 39, 94, 61, 63,  3],
       [48, 54, 87, 30, 38, 64,  1, 88, 58, 99],
       [75, 79, 31, 71, 71, 62, 55, 20, 24, 36]])

# Max: Finds the largest number.
# Min: Finds the smallest number.
# Mean: Finds the average of all numbers.
# Median: Finds the middle value when the numbers are sorted.

In [70]:
arr.max()

5

In [71]:
arr.min()

0

In [72]:
arr.mean()

2.5

In [74]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

- its an error bcoz, it is not imported from the lib

In [75]:
from numpy import *
a = array([1,2,3,4,5])
median(a)

3.0

# reshape() function
- reshape() is a function in NumPy that allows you to change the shape of an array without changing its data.

In [77]:
arr

array([0, 1, 2, 3, 4, 5])

In [78]:
arr.reshape(2,3) # it's reshaping in 2 rows and 3 col

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [80]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

- its an error bcoz, it can't change / replace / remove the values from an array

# Order in Reshaping: 'C', 'A', 'F' in NumPy
- When you reshape a NumPy array, you can specify how the data should be read and written to the new shape. The order parameter controls this.
- 'C': C-style row-major order (default)
- 'A': Fortran-style column-major order (column-wise)
- 'F': Fortran-style order (column-major)

In [81]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
arr.reshape(3,2,order='F') 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [84]:
arr.reshape(3,2,order='A') # order 'C' & 'A' are almost gives the similar output

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing 
- Indexing in NumPy allows you to access and modify specific elements or slices of an array.

In [88]:
mat = np.arange(0,100).reshape(10,10) # here its printing a matrix of values from 0 - 100, which is reshaped in 10*10 matrix
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
# created variales
row = 4
col = 5

In [90]:
row

4

In [91]:
col

5

In [92]:
mat[row,col] # it returns a value from a matrix based on values of row and col

45

In [93]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
# with slice
mat[:,col] # returns the 5th col of a matrix

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [95]:
mat[row,:] # returns the 4th row of a matrix

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [96]:
mat[0:10:3] # (start, stop, step)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [99]:
mat[2:6,2:4] # (row, col)

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [100]:
mat[1:2,2:4]

array([[12, 13]])

In [103]:
mat[2:3,2:3]

array([[22]])

# Masking in NumPy
- Masking is a technique used in NumPy to filter or select elements from an array based on specific conditions.
- also called as filter

In [104]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [105]:
id(mat) # address of matrix

2701460007280

In [106]:
mat < 50 # returns "True", if the values of matrix are lessthan 50, else returns "false"

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [107]:
mat > 50 # returns "false", if the values of matrix are Morethan 50, else returns "True"

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [109]:
mat == 50 # only retues "ture", if the values is equal to 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [111]:
mat[mat==50] # returnd the values in matrix which is equal to 50

array([50])

In [112]:
a1 = mat[mat<50] # returns the values which are lesstha to 50
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [114]:
a2 = mat[mat>50]  # returns the values which are morethan to 50
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [115]:
a3 = mat[mat>=50]  # returns the values which are morethan & equal to 50
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])